import Head from "next/head";

import { ConnectButton } from "@rainbow-me/rainbowkit";
import { Balance, Claim, Deposit } from "../components/contract";

export default function Home() {
  return (
    <div className={""}>
      <Head>
        <title>Time Locked Wallet</title>
        <meta name="description" content="Generated by npx create-web3" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header style={{ padding: "1rem" }}>
        <ConnectButton />
      </header>

      <main
        style={{
          minHeight: "60vh",
          flex: "1",
          display: "flex",
          flexDirection: "column",
          justifyContent: "center",
          alignItems: "center",
        }}
      >
        <Balance />
        <Deposit />
        <Claim />
      </main>
    </div>
  );
}
