import Head from "next/head";

import { ConnectButton } from "@rainbow-me/rainbowkit";
import { Balance, Claim, Deposit } from "../components/contract";
import { useState } from "react";
import contracts from "@/contracts/hardhat_contracts.json";
import { NATIVE_TOKEN_ADRESS, NETWORK_ID } from "@/config";

export default function Home() {
  const chainId = Number(NETWORK_ID);

  const [tokenAddress, setTokenAddress] = useState("");
  const allContracts = contracts as any;

  const testUSDCAddress = allContracts[chainId][0].contracts.TestUSDC.address;

  return (
    <div className={""}>
      <Head>
        <title>Time Locked Wallet</title>
        <meta name="description" content="Generated by npx create-web3" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header style={{ padding: "1rem" }}>
        <ConnectButton />
      </header>

      <main
        style={{
          minHeight: "60vh",
          flex: "1",
          display: "flex",
          flexDirection: "column",
          justifyContent: "center",
          alignItems: "center",
        }}
      >
        <select
          value={tokenAddress}
          onChange={(e) => setTokenAddress(e.target.value)}
        >
          <option value="">Select a Token</option>
          <option value={NATIVE_TOKEN_ADRESS}>ETH</option>
          <option value={testUSDCAddress}>TestUSDC</option>
        </select>
        <Balance tokenAddress={tokenAddress} />
        <Deposit tokenAddress={tokenAddress} />
        <Claim tokenAddress={tokenAddress} />
      </main>
    </div>
  );
}
